package dominio;
// Generated 19/03/2014 01:45:43 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  extends EntidadeDominio  implements java.io.Serializable {


     
     private String nome;
     private Boolean habilitado;
     private Set materials = new HashSet(0);

    public Categoria() {
    }

    public Categoria(String nome, Boolean habilitado, Set materials) {
       this.nome = nome;
       this.habilitado = habilitado;
       this.materials = materials;
    }
   
    public Categoria(Integer id) {
        this.setId(id);
        
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Boolean getHabilitado() {
        return this.habilitado;
    }
    
    public void setHabilitado(Boolean habilitado) {
        this.habilitado = habilitado;
    }
    public Set getMaterials() {
        return this.materials;
    }
    
    public void setMaterials(Set materials) {
        this.materials = materials;
    }




}


