package dominio;
// Generated 19/03/2014 01:45:43 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  extends EntidadeDominio  implements java.io.Serializable {


     private Date dataPrazo;
     private Short status;
     private String nota_fiscal;
     private Set compraMaterials = new HashSet(0);
     private Set cotacaos = new HashSet(0);

    public Compra() {
    }
    
    public Compra(Integer id) {
        this.setId(id);
        
    }
    
    public Compra(Date dataPrazo, Short status, Set compraMaterials, Set cotacaos) {
       this.dataPrazo = dataPrazo;
       this.status = status;
       this.compraMaterials = compraMaterials;
       this.cotacaos = cotacaos;
    }
   
    
    public Date getDataPrazo() {
        return this.dataPrazo;
    }
    
    public void setDataPrazo(Date dataPrazo) {
        this.dataPrazo = dataPrazo;
    }
    public Short getStatus() {
        return this.status;
    }
    
    public void setStatus(Short status) {
        this.status = status;
    }
    public Set getCompraMaterials() {
        return this.compraMaterials;
    }
    
    public void setCompraMaterials(Set compraMaterials) {
        this.compraMaterials = compraMaterials;
    }
    public Set getCotacaos() {
        return this.cotacaos;
    }
    
    public void setCotacaos(Set cotacaos) {
        this.cotacaos = cotacaos;
    }

    public String getNotaFiscal() {
        return nota_fiscal;
    }

    public void setNotaFiscal(String nota_fiscal) {
        this.nota_fiscal = nota_fiscal;
    }




}


