package dominio;
// Generated 19/03/2014 01:45:43 by Hibernate Tools 3.6.0



/**
 * CompraMaterial generated by hbm2java
 */
public class CompraMaterial extends EntidadeDominio implements java.io.Serializable {


     
     private Material material;
     private Compra compra;
     private Float quantidade;

    public CompraMaterial() {
    }
    
    
    public CompraMaterial(Material material, Compra compra, Float quantidade) {
       this.material = material;
       this.compra = compra;
       this.quantidade = quantidade;
    }
   
    
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Float getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Float quantidade) {
        this.quantidade = quantidade;
    }




}


