package dominio;
// Generated 19/03/2014 01:45:43 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Material generated by hbm2java
 */
public class Material extends EntidadeDominio  implements java.io.Serializable {


     
     private Categoria categoria;
     private String nome;
     private Set compraMaterials = new HashSet(0);
     private Set cotacaoMaterials = new HashSet(0);

    public Material() {
    }
    public Material(Integer id) {
        this.setId(id);
        
    }
    public Material(Categoria categoria, String nome, Set compraMaterials, Set cotacaoMaterials) {
       this.categoria = categoria;
       this.nome = nome;
       this.compraMaterials = compraMaterials;
       this.cotacaoMaterials = cotacaoMaterials;
    }
   
    
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getCompraMaterials() {
        return this.compraMaterials;
    }
    
    public void setCompraMaterials(Set compraMaterials) {
        this.compraMaterials = compraMaterials;
    }
    public Set getCotacaoMaterials() {
        return this.cotacaoMaterials;
    }
    
    public void setCotacaoMaterials(Set cotacaoMaterials) {
        this.cotacaoMaterials = cotacaoMaterials;
    }




}


